#!/usr/bin/env bash
# This script restores /etc/hosts to its original backup

if [ -f /etc/hosts.bak ]; then
  sudo cp /etc/hosts.bak /etc/hosts
  echo "Hosts file restored."
else
  echo "Backup not found."
fi
